export const AIRTABLE_SCHEMA = {
  baseId: 'app4MC2VM6q6uHQC1',
  customers: {
    table: 'tblV06fupa7zHeQxL',
    fields: {
      customerId: 'fldLv7Tt4wDcGLRsu',
      fullName: 'fldMOZbzP64GnEDCW',
      email: 'fldm0UiiEvxVVZ6lN',
      favoriteGenres: 'fldCv9fmuegcBIv8o',
      readingProfile: 'fld2AWYzbtmalqEO4',
      customerSummary: 'fldpOvypJ96YKfnsb',
      recommendationGate: 'fldbuFYrV556kQuPE',
      orders: 'fld0uHfB3bI29yHz0',
    },
  },
  catalog: {
    table: 'tblq0X5lwJi5HEOa6',
    fields: {
      title: 'fldREySki4LMzl7Qd',
      productId: 'fldSKtEGn9FmhJlm8',
      author: 'fldLPhYIvtBAtpnWR',
      genres: 'fldx07FFzXIxiBiVr',
      formats: 'fldv2eTAUUN0VjX0T',
      description: 'fldaOGSqI6AJVs5zQ',
      moodTags: 'fld5apqQnDTLkX6uf',
      pitch: 'fldA3krQACsTf6SaH',
      purchasePrice: 'fldiTrwtnaNKeuTiC',
      stock: 'fldpblAGXreSoSdMg',
      stockStatus: 'fldBltV3DzSZjaNzn',
    },
  },
  orders: {
    table: 'tblnnh0fQioZibQ53',
    fields: {
      orderId: 'fldkm3mgk6duWcaUP',
      orderDate: 'fldTiyxrg8UQuCOFZ',
      status: 'fldcykC1N4LNITXZp',
      carrier: 'fld58Ji7n2NuEsLyq',
      estimatedDelivery: 'fldrFxTGOMhE13kc5',
      deliveredOn: 'fldEYMsych84ad6mR',
      statusSummary: 'fldv6ryKSu7fGTc9T',
      lineItems: 'fldUrbjAf5SRL14St',
      total: 'fld13ZYTZzyzfz8U3',
    },
  },
  lineItems: {
    table: 'tbl7cZsg5Pcn4Wq2i',
    fields: {
      lineId: 'fldJz8t1K4io3KgNS',
      unitPrice: 'fldtXvfMSQ7CQWKuS',
      format: 'fldC2AKEv9yeYANgy',
      product: 'fldE4rYEvw2qwcdhK',
      returnEligible: 'fldrJo5szSCKPUeh4',
    },
  },
  recommendations: {
    table: 'tblzACpD2xtN8AdGS',
    fields: {
      recId: 'fldhork7VlVt6hnjj',
      reasoning: 'fld8eaA7VQfbLdhgC',
      confidence: 'fldOWTKeRvTOgbGnv',
      rank: 'fldvMIiNjXknJPmll',
      status: 'fldEB9wFkGPEOjZgJ',
      customer: 'flddCuUsK69c2unjR',
      book: 'flddYSOPEHEBouaMF',
      displayEligible: 'fldyQnQknPxF9e8K4',
      suppressionReason: 'flduPt7SFs8SaaoAo',
      blockingCases: 'fldqGH100kNFkRYbv',
    },
  },
  supportCases: {
    table: 'tbl2N4FWOeF7WrXX7',
    fields: {
      caseId: 'fld8QHVsaELEnM2dV',
      customerKey: 'fldzqIXa3y3UqpbYp',
      contactEmail: 'fldY0chDMkrub44q4',
      openedAt: 'fldjE3mEHXp6ZgNtp',
      status: 'fldoaNtgmQmDk32dF',
      primaryIntent: 'fldmQTgeBcmSR8avp',
      clarificationNeeded: 'fld6Jbgs08tPTh3ZZ',
      fullTranscript: 'fldopArKPABUR41KR',
      conversationState: 'fldBvc2uu88ehLGw1',
      verificationStatus: 'fldKlLmzMK8AfGZRs',
      caseSummary: 'fldTK2HSGKCT9uXio',
      nextBestAction: 'fldPqgDUupP869U53',
      language: 'fldR8l9U7xylYRvyG',
      notes: 'fldYQoUdjo5hgJi2T',
      customer: 'fldIfx013TjRKZucc',
    },
  },
  policies: {
    table: 'tblIpcgLdiaGj7yA0',
    fields: {
      policyId: 'fldSLg0xaQ5Td1ot1',
      name: 'fldSQWNIU1vegYuQb',
      category: 'fldqOG3cVQAHRP2Zo',
      fullText: 'fldDbnYDfWW8eWpaf',
      shortAnswer: 'fldl5s1WqGXNMiZ6d',
      keywords: 'fldgNs2U6wTEwxXBP',
      status: 'fldqgS3vEAflwD2eH',
    },
  },
} as const;

